//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrators()
        {
            this.Administers = new HashSet<Administers>();
        }

        [Key]
        [DisplayName("管理員編號")]
        public int AdministratorID { get; set; }

        [DisplayName("管理員姓名")]
        [Required]
        [StringLength(30, ErrorMessage = "姓名不得超過30字")]
        public string Name { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "請填寫Email作為管理員帳號")]
        [DataType(DataType.EmailAddress)]
        [StringLength(64, ErrorMessage = "帳號不得超過64字")]
        public string Email { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "請填寫密碼")]
        [MinLength(8, ErrorMessage = "密碼最少8碼")]
        [MaxLength(30, ErrorMessage = "密碼最多30碼")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("權限開放")]
        [Required]
        public bool Authorize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administers> Administers { get; set; }
    }
}
