//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Administrators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrators()
        {
            this.Administers = new HashSet<Administers>();
        }
        
        [DisplayName("管理員編號")]
        public int AdministratorID { get; set; }
        
        [DisplayName("管理員姓名")]
        public string Name { get; set; }
        
        [DisplayName("帳號")]
        [CheckAccont(ErrorMessage = "此帳號已註冊過")]
        public string Email { get; set; }
        
        [DisplayName("密碼")]
        public string Password { get; set; }
        
        [DisplayName("權限開放狀態")]
        public bool Authorize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administers> Administers { get; set; }


        //自訂驗證規則
        public class CheckAccont : ValidationAttribute
        {
            public override bool IsValid(object value)
            {
                ReserveRobotNewEntities1 db = new ReserveRobotNewEntities1();
                var Admaccount = db.Administrators.Where(a => a.Email == value.ToString()).FirstOrDefault();
                return (Admaccount == null) ? true : false;
            }
        }
    }
}
