//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Administers
    {
        [Key]
        [DisplayName("管理編號")]
        public int AdministerID { get; set; }

        [DisplayName("管理員編號")]
        [Required]
        public int AdministratorID { get; set; }

        [DisplayName("會員編號")]
        [Required]
        public int MemberID { get; set; }

        [DisplayName("封鎖")]
        [Required]
        public bool Blocks { get; set; }

        [DisplayName("封鎖原因")]
        [StringLength(255, ErrorMessage = "封鎖原因不得超過255字")]
        public string Reason { get; set; }
    
        public virtual Administrators Administrators { get; set; }
        public virtual Members Members { get; set; }
    }
}
