//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        public int ReservationID { get; set; }
        public int MemberID { get; set; }
        public int RestaurantID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Adult { get; set; }
        public string Child { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<System.TimeSpan> BookTime { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
